### ISSUE TITLE
/ClaimsList Doesn't Work in Latest Version

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [RoboMWM/ClaimlistClassifier#2]
Once I saw the plugin had been updated I updated it on my server too. But now /claimslist doesn't work. updated to 1.3.6. I'm using Spigot 1.12.2.

To be more exact, /claimslist works but doesn't show the claim names: https://gyazo.com/5d3a1bbd037bcee154a686978342677f

**Edit:** I just downgraded to version 1.2.6 and it still isn't showing claim names in /claimsList. I even tried naming a claim again and it said it successfully named the claim but when I did /claimsList it did not show any named claims.. Please fix.

**Edit 2:** names.data file if needed: https://pastebin.com/B4AU3jvr

**Comment by RoboMWM** [comment]
Check commands.yml, maybe you mapped the command elsewhere? Server start log would help too.

**Comment by PiggiesGoSqueal** [comment]
**Original Response:**
It's not due to commands.yml: https://pastebin.com/JznGEHJZ

Plus it worked fine with an older version of the plugin but when I deleted that jar and uploaded the new 1, it stopped working. I didn't change anything else. Then when I deleted the new jar and uploaded an older 1 I just downloaded from github, it still didn't work which made me confused. 

latest.log when using v1.2.9 of plugin: https://pastebin.com/NtJApfDs

latest.log when using v1.3.6 from [this](https://ci.appveyor.com/project/RoboMWM39862/claimlistclassifier/build/8/artifacts) link: https://pastebin.com/06ersiKt

Example of naming a claim and viewing /claimslist using v1.3.6:
https://gyazo.com/a5c8038cff9f0adaaed13d31f58aed04

When I tried using /claimname on v1.2.9 and deleted the old claimslistclassifier folder to let it regenerate, it gave this console error: https://pastebin.com/B6TcDxU5
**==========================================**
**New Response:**
Just saw a post you tagged me in. You said I never responded but I don't recall being contacted other than posts I did reply too...?
https://gyazo.com/70bd87b2ea7fcc73cd6154e56dec1bc4
You also stated you removed the feature(s) I requested from the plugin and would create a new project for future things..? :I
https://gyazo.com/bc568833ef8fff65d7633ac14c111972
**= = =**
**Okay, to clear up this mess, I'll pay you $20 to create a different project (within a reasonable amount of time) for the features I wanted so NullCase doesn't get annoyed on Spigot and have you disable what I requested.. My Discord is PiggiesGoSqueal#5552 if needed (contact me when finished and remind me of payment if you're interested). Please note: I check Discord more than Github, Spigot, or MC-Market. It's the best way to contact me.**

**Features:**
1. Asking a confirmation for players before they abandon all their claims and an option to edit the message in config like in claimslistclassifer config: https://pastebin.com/9Z0ecNrY
2. A way for a player to view the claims they're added to but not owner of. (/TrustedClaimsList)
3. /NameClaim (NewName) & /ClaimName (NewName) command for naming claims to make it easier to identify in /claimslist.
4. Adding a command that allows players to list information about their claim such as members added, the claim name, and which players have permission to add other players etc.
5. Preferably a way to keep all my currently named claims so I don't have to get my players to rename their claims. https://pastebin.com/skFf7n5T

The plugin would **need** to be dedicated to my stuff as well. In other words, not a place to dump other people's suggestions related to GriefPrevention.

**Comment by RoboMWM** [comment]
There is a dumcord link on my requests page, and the #robomwm channel in there is bridged to IRC, where I can be best reached.

As for your error, it's because you are using an older version of GP. You need to use the **dev build of GriefPrevention** that's listed in the v1.1.1 release of ClaimlistClassifier if you still wish to use GP on 1.12.2: https://github.com/RoboMWM/ClaimlistClassifier/releases/tag/1.1.1

**Comment by RoboMWM** [comment]
Ok, read back and I do see that you did respond, but I never received feedback on any of the features I implemented, which was the response I was looking for; hence why I did not recall a response as per the posts you screenshotted. https://www.spigotmc.org/threads/requests-for-robomwm.293977/page-10#post-3016028

Were the features I implemented working as intended??

**Comment by RoboMWM** [comment]
Recapped here with proposal https://www.spigotmc.org/threads/requests-for-robomwm.293977/page-13#post-3170429

**Comment by PiggiesGoSqueal** [comment]
Ah okay thanks, I responded on Spigot:
https://www.spigotmc.org/threads/requests-for-robomwm.293977/page-14#post-3170848
