### ISSUE TITLE
there any placeholder to use with GriefPreventionTitles?

### ISSUE THREAD

**Issue by alexribeirodesa** [RoboMWM/ClaimlistClassifier#23]
I'm using the GriefPreventionTitles, and I want to use the claimclassifier to give names to the claim to show with GriefPreventionTitles, like "Player Shop", can I do that?

**Comment by RoboMWM** [comment]
I haven't added any placeholder support in this plugin. Anyone else is free to PR this though.

**Comment by alexribeirodesa** [comment]
I'll try to do that :)
