### ISSUE TITLE
[Bug] Latest version sending inaccurate mail

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [RoboMWM/ClaimlistClassifier#3]
So I'm using the latest version of the plugin and I noticed it is mailing all inactive players:
Your old claims have expired due to inactivity. A grace period for new claims can be checked by typing the command §a/claimexpire check

But in my GriefPrevention config settings I made sure claims never expire so that mail being sent out is inaccurate. Could you please add a config option to disable this feature, as I'd rather not cause unnecessary confusion/panic for those that come back after being inactive for a while. 

latest.log when using v1.3.6 from this link: https://pastebin.com/06ersiKt
Grief Prevention config: https://pastebin.com/tBcQLjJm

Thanks!

**UPDATE: Please read this (https://github.com/RoboMWM/ClaimlistClassifier/issues/2) post first as if you do what it says here then this issue can be closed.**

**Comment by RoboMWM** [comment]
Actually good catch, this is a bug in GP. It's firing the event all the time regardless if the claim is actually supposed to expire or not - behaving more as a ExpireClaimCheckEvent.
