### ISSUE TITLE
[request] Admins click /claimslist to teleport to claim.

### ISSUE THREAD

**Issue by TomLewis** [RoboMWM/ClaimlistClassifier#4]
First off, I had no idea this existed, and it works with my 16.8! which is amazing! This will 100% be going to my live server.
Via https://github.com/TechFortress/GriefPrevention/issues/134

For admins to quickly find a users claim and teleport to it.

- Allow admins to click on claims in /claimslist to teleport to them! This is a bit of a no-brainer for faster admin tools, give it a permission too, maybe show some information when clicking for non-admins. /claimslist is just a mess for anyone to understand at present. this could really be tided up.

**Comment by RoboMWM** [comment]
see response https://www.spigotmc.org/threads/requests-for-robomwm.293977/page-18#post-3212400

**Comment by RoboMWM** [comment]
Done in 1.6.
