### ISSUE TITLE
Unexpected exception while parsing console command

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/ClaimlistClassifier#7]
10.10 08:37:30 [Server] WARN Unexpected exception while parsing console command "claimexpire check  AteUrC00ki35"
10.10 08:37:30 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claimexpire' in plugin ClaimslistClassifier v1.3.8
10.10 08:37:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:691) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:478) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:435) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
10.10 08:37:30 [Server] INFO Caused by: java.lang.IllegalArgumentException: Name cannot be blank
10.10 08:37:30 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1443) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO at me.robomwm.claimslistclassifier.command.ClaimExpireCommand.getPlayer(ClaimExpireCommand.java:53) ~[?:?]
10.10 08:37:30 [Server] INFO at me.robomwm.claimslistclassifier.command.ClaimExpireCommand.onCommand(ClaimExpireCommand.java:69) ~[?:?]
10.10 08:37:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-355]
10.10 08:37:30 [Server] INFO ... 8 more

**Comment by RoboMWM** [comment]
Claimslistclassifier is on 1.5? Also, wrap stacktraces with three backticks

    ```
    like so
    ```

**Comment by RoboMWM** [comment]
As for that error, no idea why it's claiming the name is blank. It's passing in the proper array element to getOfflinePlayer... does this happen for all players or just that one?

**Comment by NullCase** [comment]
just that one time.

Sorry, classifier is on 1.5?

**Comment by RoboMWM** [comment]
Gonna guess your server wasn't able to resolve that username for whatever reason that one time then. And yes it is, 1.4 added a config (with claimexpire default disabled, the other two enabled), 1.5 added the two other features (default disabled). You mentioned that you were going to test it out on your next update or whatever on the spigot thread.

**Comment by NullCase** [comment]
OK, thanks @RoboMWM I'll look again for a more recent version.

I'm sorry, it seems like i have a way of wasting your time with speculation. Still, after that error I typed out the name and it worked. It seems like copying the name from our site might have included an extra space in front... something. But it's a weird one.

**Comment by RoboMWM** [comment]
Nah you didn't waste any time. Those who waste my time are those who report an error but provide absolutely no other useful information, or who don't read the documentation. You do provide information, so don't worry about it c:
