### ISSUE TITLE
Where are the JAR builds?

### ISSUE THREAD

**Issue by TomLewis** [RoboMWM/ClaimlistClassifier#8]
I can only seem to see the source code on https://github.com/RoboMWM/ClaimslistClassifier/releases

Where are the jar's being served?

**Comment by RoboMWM** [comment]
I believe I mentioned a link to the CI publishing the jars on one of your other issues.

**Comment by TomLewis** [comment]
Haha oh yeah, whoops. Can I commit that to the readme so I don't forget again? 80+ plugins here, trying to keep track is hilarious sometimes.

**Comment by RoboMWM** [comment]
I'll probably post this plugin on bukkitdev and spigotmc sometime soon.
